# Generated by Django 5.2.5 on 2025-09-01 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_yes', models.TextField()),
                ('answer_no', models.TextField()),
                ('follow_up_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recap_text', models.TextField(blank=True, null=True)),
                ('bonus_tip', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('response_text', models.TextField()),
                ('allow_user_input', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_options', to='chatbot.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.topic'),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('question_index', models.IntegerField(default=0)),
                ('answered_questions', models.ManyToManyField(blank=True, to='chatbot.question')),
                ('current_topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_topic_sessions', to='chatbot.topic')),
                ('expecting_free_text_for_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.followupoption')),
                ('finished_topics', models.ManyToManyField(blank=True, related_name='finished_by_users', to='chatbot.topic')),
                ('restart_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restart_topic_sessions', to='chatbot.topic')),
            ],
        ),
    ]
